# Generated by Django 3.2 on 2022-08-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_num',
            field=models.CharField(max_length=100, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Домашний адрес'),
        ),
        migrations.AlterField(
            model_name='work',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Организация'),
        ),
    ]
