# Generated by Django 3.2 on 2022-08-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='postalZip',
            field=models.CharField(max_length=100, verbose_name='Почтовый индекс'),
        ),
    ]
